<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../../build/Settings/NuGetVersioning.props" />

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <EnableArchitecturalLevelAnalyzer>false</EnableArchitecturalLevelAnalyzer>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RonSijm.AnaalIJzer.Core.Indicators\RonSijm.AnaalIJzer.Core.Indicators.csproj" />
    </ItemGroup>

</Project>
