using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RonSijm.AnaalIJzer.Definitions;

namespace RonSijm.AnaalIJzer.Snapshots;

public static partial class ArchitectureEditorSnapshotService
{
	private static bool IsGenerated(Document document, SyntaxNode syntaxRoot, CancellationToken cancellationToken)
	{
		if (document.FilePath is { } filePath)
		{
			if (IsGeneratedFilePath(filePath))
			{
				return true;
			}
		}

		var text = syntaxRoot.SyntaxTree.GetText(cancellationToken);
		var firstSpan = TextSpan.FromBounds(0, Math.Min(text.Length, 512));
		var result = text.ToString(firstSpan).IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0;

		return result;
	}

	private static bool IsGenerated(SyntaxTree syntaxTree, CancellationToken cancellationToken)
	{
		if (IsGeneratedFilePath(syntaxTree.FilePath))
		{
			return true;
		}

		var text = syntaxTree.GetText(cancellationToken);
		var firstSpan = TextSpan.FromBounds(0, Math.Min(text.Length, 512));
		var result = text.ToString(firstSpan).IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0;

		return result;
	}

	private static bool IsGeneratedFilePath(string? filePath)
	{
		if (string.IsNullOrWhiteSpace(filePath))
		{
			return false;
		}

		var fileName = Path.GetFileName(filePath);
		var result = fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
		             || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
		             || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);

		return result;
	}

	private readonly struct CallerInfo(string typeName, string layerPath, LayerMatch match)
    {
        public string TypeName { get; } = typeName;

        public string LayerPath { get; } = layerPath;

        public LayerMatch Match { get; } = match;
    }
}
