using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace RonSijm.AnaalIJzer.ObservedDependencies;

public static class GeneratedCodeDetector
{
	public static bool IsGenerated(SyntaxTree syntaxTree, CancellationToken cancellationToken)
	{
		var filePath = syntaxTree.FilePath;
		if (!string.IsNullOrWhiteSpace(filePath))
		{
			var normalizedPath = filePath.Replace('/', '\\');
			var fileName = Path.GetFileName(filePath);
			if (normalizedPath.Contains("\\obj\\", StringComparison.OrdinalIgnoreCase)
			    || fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
			    || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase))
			{
				return true;
			}

			if (fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase))
			{
				return true;
			}
		}

		var text = syntaxTree.GetText(cancellationToken);
		var prefixLength = Math.Min(text.Length, 512);
		var result = text.ToString(new TextSpan(0, prefixLength)).Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);

		return result;
	}
}
