<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="../../../build/Settings/NuGetVersioning.props" />

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <EnableArchitecturalLevelAnalyzer>false</EnableArchitecturalLevelAnalyzer>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RonSijm.AnaalIJzer.ConfigurationEditing\RonSijm.AnaalIJzer.ConfigurationEditing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>RonSijm.AnaalIJzer.GraphEditor.Wpf</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>RonSijm.AnaalIJzer.GraphApplication.Tests</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>RonSijm.AnaalIJzer.GraphEditor.Wpf.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>
