using System.Text;
using System.Xml.Linq;

namespace RonSijm.AnaalIJzer.Outputs.Configuration;

internal static partial class ArchitectureConfigurationExplainer
{
	private static void AppendAssemblyAttributePolicy(StringBuilder sb, XElement element, int depth)
	{
		AppendLine(sb, depth, "- Assembly-attribute policy checks semantic attributes emitted for the compiled assembly, including attributes generated by the project SDK.");
		AppendDescription(sb, element, depth + 1);
		foreach (var container in element.Elements().Where(child => child.Name.LocalName is "Allowed" or "Forbidden"))
		{
			var mode = container.Name.LocalName == "Allowed" ? "allows only" : "blocks";
			AppendLine(sb, depth + 1, "- " + mode + " matching selected assembly attributes.");
			AppendDescription(sb, container, depth + 2);
			foreach (var attribute in container.Elements("Attribute"))
			{
				AppendLine(sb, depth + 2, "- Attribute " + FormatMatcher(attribute) + ".");
				AppendDescription(sb, attribute, depth + 3);
				foreach (var argument in attribute.Elements("Argument"))
				{
					var selector = argument.Attribute("index")?.Value is { } index
						? "argument #" + index
						: "argument '" + (argument.Attribute("name")?.Value ?? "(missing name)") + "'";
					AppendLine(sb, depth + 3, "- Requires " + selector + " " + FormatMatcher(argument) + ".");
					AppendDescription(sb, argument, depth + 4);
				}
			}
		}
	}
}
