using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using RonSijm.AnaalIJzer.ObservedDependencies;

namespace RonSijm.AnaalIJzer.Core.Observations.Tests;

public sealed class ObservationHelpersTests
{
	[Theory]
	[InlineData("D:/src/obj/Generated.cs", "class Example { }")]
	[InlineData("D:/src/Form.designer.cs", "class Example { }")]
	[InlineData("D:/src/Generated.cs", "// <auto-generated>\nclass Example { }")]
	public void GeneratedCodeDetector_RecognizesKnownGeneratedPatterns(string path, string source)
	{
		var cancellationToken = TestContext.Current.CancellationToken;
		var tree = CSharpSyntaxTree.ParseText(SourceText.From(source), cancellationToken: cancellationToken, path: path);

		var result = GeneratedCodeDetector.IsGenerated(tree, cancellationToken);

		result.Should().BeTrue();
	}

	[Fact]
	public void LocationExtensions_ReturnSourcePathAndLineNumber()
	{
		const string source = """
		                      namespace Demo;
		                      public class Example { }
		                      """;
		var cancellationToken = TestContext.Current.CancellationToken;
		var tree = CSharpSyntaxTree.ParseText(SourceText.From(source), cancellationToken: cancellationToken, path: "D:/src/Example.cs");
		var root = tree.GetRoot(cancellationToken);
		var declaration = root.DescendantNodes().OfType<ClassDeclarationSyntax>().Single();
		var location = declaration.Identifier.GetLocation();

		location.GetSourcePath().Should().Be("D:/src/Example.cs");
		location.GetSourceLineNumber().Should().Be(2);
	}

	[Fact]
	public void ObservedDependencyCollector_DeduplicatesAndOrdersRecordedDependencies()
	{
		var collector = new ObservedDependencyCollector();
		var alphaLocation = GetClassIdentifierLocation("public class Alpha { }", "D:/src/Alpha.cs");
		var betaLocation = GetClassIdentifierLocation("public class Beta { }", "D:/src/Beta.cs");

		collector.Record("BetaCaller", "Beta", "GammaDependency", "Gamma", "Constructor", betaLocation);
		collector.Record("AlphaCaller", "Alpha", "BetaDependency", "Beta", "Field", alphaLocation);
		collector.Record("AlphaCaller", "Alpha", "BetaDependency", "Beta", "Field", alphaLocation);

		var snapshot = collector.GetSnapshot();

		snapshot.Should().HaveCount(2);
		snapshot[0].CallerLayer.Should().Be("Alpha");
		snapshot[0].CallerTypeName.Should().Be("AlphaCaller");
		snapshot[1].CallerLayer.Should().Be("Beta");
		snapshot[1].CallerTypeName.Should().Be("BetaCaller");
	}

	private static Location GetClassIdentifierLocation(string source, string path)
	{
		var cancellationToken = TestContext.Current.CancellationToken;
		var tree = CSharpSyntaxTree.ParseText(SourceText.From(source), cancellationToken: cancellationToken, path: path);
		var root = tree.GetRoot(cancellationToken);
		var declaration = root.DescendantNodes().OfType<ClassDeclarationSyntax>().Single();
		var result = declaration.Identifier.GetLocation();

		return result;
	}
}
