<Project Sdk="Microsoft.NET.Sdk">


    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <EnableArchitecturalLevelAnalyzer>false</EnableArchitecturalLevelAnalyzer>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\RonSijm.AnaalIJzer.Core.Indicators\RonSijm.AnaalIJzer.Core.Indicators.csproj" />
        <ProjectReference Include="..\RonSijm.AnaalIJzer.GraphModel\RonSijm.AnaalIJzer.GraphModel.csproj"
                          SetTargetFramework="TargetFramework=netstandard2.0" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
        <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
    </ItemGroup>

</Project>
