<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>Legacy.Transport</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableArchitecturalLevelAnalyzer>false</EnableArchitecturalLevelAnalyzer>
  </PropertyGroup>

</Project>
