using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using RonSijm.AnaalIJzer.Core.Findings;
using RonSijm.AnaalIJzer.Diagnostics;
using AnalyzerConfig = RonSijm.AnaalIJzer.Core.RuntimeConfig.Config.Model.AnalyzerConfig;

namespace RonSijm.AnaalIJzer.Engine.Analysis.AssemblyAttributes;

/// <summary>Checks semantic assembly attributes, including attributes generated by the project SDK.</summary>
internal static class AssemblyAttributePolicyAnalyzer
{
	internal static void AnalyzeCompilation(CompilationAnalysisContext context, AnalyzerConfig config)
	{
		foreach (var attribute in context.Compilation.Assembly.GetAttributes())
		{
			var evaluation = config.AssemblyAttributePolicies.Evaluate(attribute);
			if (evaluation is null)
			{
				continue;
			}

			Report(context, attribute, evaluation.Value);
		}
	}

	private static void Report(CompilationAnalysisContext context, AttributeData attribute, RonSijm.AnaalIJzer.Core.AssemblyAttributes.Model.AssemblyAttributePolicyEvaluation evaluation)
	{
		var rule = evaluation.Rule;
		var assemblyName = context.Compilation.AssemblyName ?? "UnknownAssembly";
		var attributeTypeName = GetAttributeTypeName(attribute);
		var location = attribute.ApplicationSyntaxReference?.GetSyntax(context.CancellationToken).GetLocation() ?? Location.None;
		var properties = ImmutableDictionary<string, string?>.Empty
			.Add(ArchitectureDiagnosticProperties.PropertyCallerTypeName, assemblyName)
			.Add(ArchitectureDiagnosticProperties.PropertyCallerLayerName, "Assembly")
			.Add(ArchitectureDiagnosticProperties.PropertyDepTypeName, attributeTypeName)
			.Add(ArchitectureDiagnosticProperties.PropertyDepLayerName, rule.DisplayName)
			.Add(ArchitectureDiagnosticProperties.PropertyDeclaredSymbolName, attributeTypeName)
			.Add(ArchitectureDiagnosticProperties.PropertyDeclarationTarget, "AssemblyAttribute")
			.Add(ArchitectureDiagnosticProperties.PropertyAssemblyAttributeTypeName, attributeTypeName)
			.Add(ArchitectureDiagnosticProperties.PropertyAssemblyAttributePolicyRule, rule.DisplayName)
			.Add(ArchitectureDiagnosticProperties.PropertyViolationReason, evaluation.Reason)
			.Add(ArchitectureDiagnosticProperties.PropertyComment, rule.Description ?? evaluation.Policy.Description)
			.Add(ArchitectureDiagnosticProperties.PropertyRuleXmlPath, rule.XmlPath)
			.Add(ArchitectureDiagnosticProperties.PropertyRuleXmlLine, rule.XmlLineNumber.ToString(System.Globalization.CultureInfo.InvariantCulture))
			.Add(ArchitectureDiagnosticProperties.PropertyRuleXmlCol, rule.XmlLinePosition.ToString(System.Globalization.CultureInfo.InvariantCulture));

		context.ReportDiagnostic(ArchitecturalDiagnostics.CreateDiagnostic(
			ArchitecturalDiagnostics.AssemblyAttributeNotAllowed,
			location,
			properties,
			assemblyName,
			attributeTypeName,
			evaluation.Reason));
	}

	private static string GetAttributeTypeName(AttributeData attribute)
	{
		var result = attribute.AttributeClass?.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat) ?? "UnknownAttribute";

		return result;
	}
}
