// ReSharper disable All - Justification: Example File
// <auto-generated />

using System;

namespace Example.GeneratedCode;

public sealed class GeneratedClockKitchen
{
	// ARCH021: this file is normally ignored, but Architecture.anl explicitly opts it into analysis.
	public DateTime GetGeneratedServingTime()
	{
		return DateTime.UtcNow;
	}
}
