using System.Collections.Immutable;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using RonSijm.AnaalIJzer.Parsing;
using RonSijm.AnaalIJzer.Diagnostics;
using AnalyzerConfiguration = RonSijm.AnaalIJzer.Model.AnalyzerConfig;

namespace RonSijm.AnaalIJzer.Tooling;

internal static partial class ApplicationConfigurationGenerator
{
	public static string ReadSchema()
	{
		using var stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(SchemaResourceName)
			?? throw new InvalidOperationException($"Embedded resource not found: {SchemaResourceName}");
		using var reader = new StreamReader(stream);
		var result = reader.ReadToEnd();

		return result;
	}

	public static Task<ImmutableArray<Diagnostic>> ValidateAsync(Compilation compilation, string configuration, string configurationPath, CancellationToken cancellationToken)
	{
		var options = new AnalyzerOptions([new GeneratedAdditionalText(configurationPath, configuration)]);
		var result = compilation.WithAnalyzers([new ArchitecturalLevelAnalyzer()], options).GetAnalyzerDiagnosticsAsync(cancellationToken);

		return result;
	}

	public static async Task<ImmutableArray<Diagnostic>> ValidateAsync(SolutionAnalysisResult solution, string configuration, string configurationPath, CancellationToken cancellationToken)
	{
		var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
		foreach (var project in solution.Projects)
		{
			var projectDiagnostics = await ValidateAsync(project.Compilation, configuration, configurationPath, cancellationToken);
			diagnostics.AddRange(projectDiagnostics);
		}

		var result = diagnostics.ToImmutable();

		return result;
	}

	public static AnalyzerConfiguration Parse(Compilation compilation, string configuration, string configurationPath, CancellationToken cancellationToken)
	{
		var additionalText = new GeneratedAdditionalText(configurationPath, configuration);
		var result = ArchitecturalConfigParser.Parse([additionalText], compilation, configurationPath, cancellationToken);

		return result;
	}

	internal static IReadOnlyList<INamedTypeSymbol> GetProjectTypes(Compilation compilation, CancellationToken cancellationToken)
	{
		var types = new List<INamedTypeSymbol>();
		CollectNamespaceTypes(compilation.Assembly.GlobalNamespace, types, cancellationToken);
		return DistinctTypes(types)
			.OrderBy(type => type.Locations.FirstOrDefault(location => location.IsInSource)?.SourceTree?.FilePath, StringComparer.OrdinalIgnoreCase)
			.ThenBy(type => type.Locations.FirstOrDefault(location => location.IsInSource)?.SourceSpan.Start ?? int.MaxValue)
			.ToArray();
	}

	private static void CollectNamespaceTypes(INamespaceSymbol namespaceSymbol, List<INamedTypeSymbol> types, CancellationToken cancellationToken)
	{
		cancellationToken.ThrowIfCancellationRequested();
		foreach (var type in namespaceSymbol.GetTypeMembers())
		{
			CollectType(type, types, cancellationToken);
		}

		foreach (var childNamespace in namespaceSymbol.GetNamespaceMembers())
		{
			CollectNamespaceTypes(childNamespace, types, cancellationToken);
		}
	}

	private static IEnumerable<INamedTypeSymbol> DistinctTypes(IEnumerable<INamedTypeSymbol> types)
	{
		var seen = new HashSet<ISymbol>(SymbolEqualityComparer.Default);
		foreach (var type in types)
		{
			if (seen.Add(type))
			{
				yield return type;
			}
		}
	}

	private static void CollectType(INamedTypeSymbol type, List<INamedTypeSymbol> types, CancellationToken cancellationToken)
	{
		if (type.DeclaringSyntaxReferences.Any(reference => !IsGenerated(reference.SyntaxTree, cancellationToken)))
		{
			types.Add(type.OriginalDefinition);
		}

		foreach (var nestedType in type.GetTypeMembers())
		{
			CollectType(nestedType, types, cancellationToken);
		}
	}

	internal static bool IsGenerated(SyntaxTree syntaxTree, CancellationToken cancellationToken)
	{
		var filePath = syntaxTree.FilePath;
		if (!string.IsNullOrWhiteSpace(filePath))
		{
			var normalizedPath = filePath.Replace('/', '\\');
			var fileName = Path.GetFileName(filePath);
			if (normalizedPath.Contains("\\obj\\", StringComparison.OrdinalIgnoreCase)
			    || fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
			    || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase))
			{
				return true;
			}
		}

		var text = syntaxTree.GetText(cancellationToken);
		var prefixLength = Math.Min(text.Length, 512);
		var result = text.ToString(new Microsoft.CodeAnalysis.Text.TextSpan(0, prefixLength)).Contains("<auto-generated", StringComparison.OrdinalIgnoreCase);

		return result;
	}
}
