<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="../../../build/Settings/NetFxCompatibleProjectTargetFramework.props" />

    <PropertyGroup>
        <TargetFrameworks>netstandard2.0;net472</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
        <EnableArchitecturalLevelAnalyzer>false</EnableArchitecturalLevelAnalyzer>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net472" Version="1.0.3" PrivateAssets="all" Condition="'$(TargetFramework)' == 'net472'" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\RonSijm.AnaalIJzer.Core.Configuration.Document\RonSijm.AnaalIJzer.Core.Configuration.Document.csproj"
                          SetTargetFramework="TargetFramework=$(NetFxCompatibleProjectTargetFramework)" />
        <ProjectReference Include="..\RonSijm.AnaalIJzer.ConfigurationEditing\RonSijm.AnaalIJzer.ConfigurationEditing.csproj"
                          SetTargetFramework="TargetFramework=$(NetFxCompatibleProjectTargetFramework)" />
    </ItemGroup>

</Project>
